### ISSUE TITLE
 All chrome windows close when trying to open a file

### ISSUE THREAD

**Issue by armandodesigns2010** [aik099/PhpStormProtocol#55] opened 2024-09-17 18:48 UTC
After clicking on "Open Microsoft Windows Based Script Host" to open the file in PhpStorm, all Chrome windows close.
![Screenshot 2024-09-17 215409](https://github.com/user-attachments/assets/c9e12e4d-43f4-445e-8dcd-beea5be016ba)

I tried on Mozilla Firefox and it works as expected, the files open in PhpStorm.

PHPStorm version: Build #PS-242.20224.361
Chrome version: 128.0.6613.138 (Official Build) (64-bit)
OS: Windows 11 Pro version 23H2 (OS Build 22631.4037)

Thanks!

**Comment by aik099** [comment] 2024-09-18 11:54
Were you having this problem before (e.g. in the previous PhpStormProtocol) version?

If this is the 1st time you're using the PhpStormProtocol, then please record a screencast in Google Chrome with Inspector opened so that I see that window closing for myself.

**Comment by armandodesigns2010** [comment] 2024-09-18 13:27
[Recording 2024-09-18 162019.zip](https://github.com/user-attachments/files/17044699/Recording.2024-09-18.162019.zip)

This is my 1st time using PhpStormProtocol, after clicking all windows Chrome close.
It works on Mozilla Firefox

Thanks

**Comment by aik099** [comment] 2024-09-18 13:47
Doesn't Google Chrome ask to restore the closed windows/last session after you open it again? If so, then it crashed while attempting to call the PhpStormProtocol app.

Looks like a bug in Google Chrome. If that is indeed so, then you have these options:

1. report a bug to Google Chrome and provide steps to reproduce it;
2. debug code in the `run_editor.js` file yourself (or ask other developers, e.g. project contributors) to identify what exactly makes Google Chrome react this way and fix it from the `run_editor.js` side.

**Comment by armandodesigns2010** [comment] 2024-09-18 14:03
![image](https://github.com/user-attachments/assets/0e2a9c0c-0f88-4efa-b4da-1b794390e27b)
Yes, it does.
I will report a bug to Google Chrome.

Thanks!

**Closed** 2024-09-18 14:06 UTC
